class Constants
  def self.generate_cost_and_usage_test_fixture
    services_in_use = [
      AMAZON_ELASTIC_COMPUTE_CLOUD_COMPUTE,
      AMAZON_RELATIONAL_DATABASE_SERVICE,
      AMAZON_ELASTICACHE,
      AMAZON_SIMPLE_STORAGE_SERVICE
    ]
    date_range = (Date.parse('2023-12-01')...Date.parse('2023-12-07')).to_a
    date_range.map do |date|
      date_total = Random.random_number(90..200)
      remaining = date_total
      {
        start: date.to_s,
        total: date_total.to_f,
        groups: services_in_use.each_with_index.map do |service, i|
          service_total = if i == services_in_use.length - 1
                            remaining
                          else
                            [Random.random_number(0..70), remaining].min
                          end
          remaining -= service_total
          [service, service_total.to_f]
        end
      }
    end
  end

  DAY_FORMAT_STR = '%Y-%m-%d'.freeze
  HOUR_FORMAT_STR = '%Y-%m-%dT%H:%M:%SZ'.freeze
  DEFAULT_AWS_REGION = 'us-west-2'.freeze
  US_EAST_1 = 'us-east-1'.freeze
  AVG_DAYS_IN_MONTH = 30.4

  GRANULARITIES = [
    DAILY = "DAILY",
    HOURLY = "HOURLY",
    MONTHLY = "MONTHLY"
  ].freeze

  GROUP_BY_OPTIONS = [
    SERVICE = "SERVICE"
  ].freeze

  METRICS = [
    NET_AMORTIZED_COST = "NetAmortizedCost"
  ].freeze

  CLIENT_TYPES = [
    COST_EXPLORER = "CostExplorer",
    STS = "STS",
    SAVINGS_PLANS = "SavingsPlans",
    RDS = "RDS",
    ELASTI_CACHE = "ElastiCache"
  ].freeze

  CLIENT_CLASS_MAPPINGS = {
    COST_EXPLORER => Aws::CostExplorer::Client,
    STS => Aws::STS::Client,
    SAVINGS_PLANS => Aws::SavingsPlans::Client,
    RDS => Aws::RDS::Client,
    ELASTI_CACHE => Aws::ElastiCache::Client
  }.freeze

  USAGE_TYPES = {
    TOP_DATA_TRANSFER: [
      "USW2-DataTransfer-Out-Bytes",
      "USW2-USE1-AWS-Out-Bytes",
      "USW2-DataTransfer-Regional-Bytes",
      "USE2-DataTransfer-Regional-Bytes",
      "USE2-DataTransfer-Out-Bytes",
      "APN2-DataTransfer-Out-Bytes",
      "APS1-DataTransfer-Out-Bytes",
      "APN1-DataTransfer-Out-Bytes",
      "SAE1-DataTransfer-Out-Bytes",
      "EUC1-DataTransfer-Out-Bytes",
      "DataTransfer-Out-Bytes",
      "APS3-DataTransfer-Out-Bytes",
      "APS2-DataTransfer-Out-Bytes",
      "EUW2-DataTransfer-Out-Bytes",
      "EU-DataTransfer-Out-Bytes",
      "USW1-DataTransfer-Out-Bytes",
      "USW2-EUW2-AWS-Out-Bytes",
      "USW2-Hst:Data-Bytes-In",
      "USW2-APN1-AWS-Out-Bytes",
      "USW2-Hst:Data-Bytes-Out",
      "USW2-APN2-AWS-Out-Bytes",
      "USW2-USW1-AWS-Out-Bytes",
      "USW2-EUC1-AWS-Out-Bytes",
      "USW2-EU-AWS-Out-Bytes",
      "USE2-USE1-AWS-Out-Bytes",
      "USE2-USW2-AWS-Out-Bytes",
      "USW2-USE2-AWS-Out-Bytes",
      "USW2-SAE1-AWS-Out-Bytes",
      "USW2-EUN1-AWS-Out-Bytes",
      "USW2-APS1-AWS-Out-Bytes",
      "USW2-APS3-AWS-Out-Bytes",
      "USW2-EUW3-AWS-Out-Bytes",
      "USW2-APS2-AWS-Out-Bytes",
      "USW2-CAN1-AWS-Out-Bytes",
      "USW2-APN3-AWS-Out-Bytes",
      "USW2-APS6-AWS-Out-Bytes",
      "USW2-CloudFrontChina-Out-Bytes",
      "USW2-EUS2-AWS-Out-Bytes",
      "USW2-APE1-AWS-Out-Bytes",
      "USW2-UGW1-AWS-Out-Bytes",
    ],
    DATA_TRANSFER: [
      "AP-DataTransfer-Out-Bytes",
      "AP-DataTransfer-Out-OBytes",
      "APN1-DataProcessing-Bytes",
      "APN1-DataTransfer-In-Bytes",
      "APN1-DataTransfer-Out-Bytes",
      "APN1-USE1-AWS-Out-Bytes",
      "APN1-USW2-AWS-In-Bytes",
      "APN1-USW2-AWS-Out-Bytes",
      "APN2-CloudFront-In-Bytes",
      "APN2-CloudFront-Out-Bytes",
      "APN2-DataProcessing-Bytes",
      "APN2-DataTransfer-In-Bytes",
      "APN2-DataTransfer-Out-Bytes",
      "APN2-DataTransfer-Regional-Bytes",
      "APN2-USE1-AWS-Out-Bytes",
      "APN2-USW1-AWS-In-Bytes",
      "APN2-USW1-AWS-Out-Bytes",
      "APN2-USW2-AWS-In-Bytes",
      "APN2-USW2-AWS-Out-Bytes",
      "APN3-DataTransfer-In-Bytes",
      "APN3-DataTransfer-Out-Bytes",
      "APN3-USE1-AWS-Out-Bytes",
      "APN3-USW2-AWS-In-Bytes",
      "APN3-USW2-AWS-Out-Bytes",
      "APS1-DataProcessing-Bytes",
      "APS1-DataTransfer-In-Bytes",
      "APS1-DataTransfer-Out-Bytes",
      "APS1-USE1-AWS-Out-Bytes",
      "APS1-USW2-AWS-In-Bytes",
      "APS1-USW2-AWS-Out-Bytes",
      "APS2-DataProcessing-Bytes",
      "APS2-DataTransfer-In-Bytes",
      "APS2-DataTransfer-Out-Bytes",
      "APS2-USE1-AWS-Out-Bytes",
      "APS2-USW2-AWS-In-Bytes",
      "APS2-USW2-AWS-Out-Bytes",
      "APS3-AFS1-AWS-In-Bytes",
      "APS3-AFS1-AWS-Out-Bytes",
      "APS3-APE1-AWS-In-Bytes",
      "APS3-APE1-AWS-Out-Bytes",
      "APS3-APN1-AWS-In-Bytes",
      "APS3-APN1-AWS-Out-Bytes",
      "APS3-APN2-AWS-In-Bytes",
      "APS3-APN2-AWS-Out-Bytes",
      "APS3-APN3-AWS-In-Bytes",
      "APS3-APN3-AWS-Out-Bytes",
      "APS3-APS1-AWS-In-Bytes",
      "APS3-APS1-AWS-Out-Bytes",
      "APS3-APS2-AWS-In-Bytes",
      "APS3-APS2-AWS-Out-Bytes",
      "APS3-APS4-AWS-In-Bytes",
      "APS3-APS4-AWS-Out-Bytes",
      "APS3-APS5-AWS-In-Bytes",
      "APS3-APS5-AWS-Out-Bytes",
      "APS3-APS6-AWS-In-Bytes",
      "APS3-APS6-AWS-Out-Bytes",
      "APS3-ATL1-AWS-In-Bytes",
      "APS3-ATL1-AWS-Out-Bytes",
      "APS3-AWS-In-Bytes",
      "APS3-AWS-Out-Bytes",
      "APS3-BOS1-AWS-In-Bytes",
      "APS3-BOS1-AWS-Out-Bytes",
      "APS3-BilledBytes",
      "APS3-CAN1-AWS-In-Bytes",
      "APS3-CAN1-AWS-Out-Bytes",
      "APS3-CHI1-AWS-In-Bytes",
      "APS3-CHI1-AWS-Out-Bytes",
      "APS3-CloudFront-In-Bytes",
      "APS3-CloudFront-Out-Bytes",
      "APS3-DEN1-AWS-In-Bytes",
      "APS3-DEN1-AWS-Out-Bytes",
      "APS3-DFW1-AWS-In-Bytes",
      "APS3-DFW1-AWS-Out-Bytes",
      "APS3-DataProcessing-Bytes",
      "APS3-DataScanned-Bytes",
      "APS3-DataTransfer-AZ-In-Bytes",
      "APS3-DataTransfer-AZ-Out-Bytes",
      "APS3-DataTransfer-In-Bytes",
      "APS3-DataTransfer-Out-Bytes",
      "APS3-DataTransfer-Regional-Bytes",
      "APS3-DataTransfer-xAZ-In-Bytes",
      "APS3-DataTransfer-xAZ-Out-Bytes",
      "APS3-EU-AWS-In-Bytes",
      "APS3-EU-AWS-Out-Bytes",
      "APS3-EUC1-AWS-In-Bytes",
      "APS3-EUC1-AWS-Out-Bytes",
      "APS3-EUC2-AWS-In-Bytes",
      "APS3-EUC2-AWS-Out-Bytes",
      "APS3-EUN1-AWS-In-Bytes",
      "APS3-EUN1-AWS-Out-Bytes",
      "APS3-EUS1-AWS-In-Bytes",
      "APS3-EUS1-AWS-Out-Bytes",
      "APS3-EUS2-AWS-In-Bytes",
      "APS3-EUS2-AWS-Out-Bytes",
      "APS3-EUW2-AWS-In-Bytes",
      "APS3-EUW2-AWS-Out-Bytes",
      "APS3-EUW3-AWS-In-Bytes",
      "APS3-EUW3-AWS-Out-Bytes",
      "APS3-ExportDataSize-Bytes",
      "APS3-IAH1-AWS-In-Bytes",
      "APS3-IAH1-AWS-Out-Bytes",
      "APS3-ILC1-AWS-In-Bytes",
      "APS3-ILC1-AWS-Out-Bytes",
      "APS3-ImportDataSize-Bytes",
      "APS3-LAS1-AWS-In-Bytes",
      "APS3-LAS1-AWS-Out-Bytes",
      "APS3-LAX1-AWS-In-Bytes",
      "APS3-LAX1-AWS-Out-Bytes",
      "APS3-MCI2-AWS-In-Bytes",
      "APS3-MCI2-AWS-Out-Bytes",
      "APS3-MEC1-AWS-In-Bytes",
      "APS3-MEC1-AWS-Out-Bytes",
      "APS3-MES1-AWS-In-Bytes",
      "APS3-MES1-AWS-Out-Bytes",
      "APS3-MIA1-AWS-In-Bytes",
      "APS3-MIA1-AWS-Out-Bytes",
      "APS3-MSP1-AWS-In-Bytes",
      "APS3-MSP1-AWS-Out-Bytes",
      "APS3-NYC1-AWS-In-Bytes",
      "APS3-NYC1-AWS-Out-Bytes",
      "APS3-NatGateway-Bytes",
      "APS3-PDX1-AWS-In-Bytes",
      "APS3-PDX1-AWS-Out-Bytes",
      "APS3-PHL1-AWS-In-Bytes",
      "APS3-PHL1-AWS-Out-Bytes",
      "APS3-PHX1-AWS-In-Bytes",
      "APS3-PHX1-AWS-Out-Bytes",
      "APS3-SAE1-AWS-In-Bytes",
      "APS3-SAE1-AWS-Out-Bytes",
      "APS3-SEA1-AWS-In-Bytes",
      "APS3-SEA1-AWS-Out-Bytes",
      "APS3-TPE1-AWS-In-Bytes",
      "APS3-TPE1-AWS-Out-Bytes",
      "APS3-UGE1-AWS-In-Bytes",
      "APS3-UGE1-AWS-Out-Bytes",
      "APS3-UGW1-AWS-In-Bytes",
      "APS3-UGW1-AWS-Out-Bytes",
      "APS3-USE1-AWS-In-Bytes",
      "APS3-USE1-AWS-Out-Bytes",
      "APS3-USE2-AWS-In-Bytes",
      "APS3-USE2-AWS-Out-Bytes",
      "APS3-USW1-AWS-In-Bytes",
      "APS3-USW1-AWS-Out-Bytes",
      "APS3-USW2-AWS-In-Bytes",
      "APS3-USW2-AWS-Out-Bytes",
      "APS3-VendedLog-Bytes",
      "APS3-VpcEndpoint-Bytes",
      "AU-DataTransfer-Out-Bytes",
      "AU-DataTransfer-Out-OBytes",
      "CA-DataTransfer-Out-Bytes",
      "CA-DataTransfer-Out-OBytes",
      "CAN1-DataTransfer-In-Bytes",
      "CAN1-DataTransfer-Out-Bytes",
      "CAN1-USE1-AWS-Out-Bytes",
      "CAN1-USW2-AWS-In-Bytes",
      "CAN1-USW2-AWS-Out-Bytes",
      "DataTransfer-In-Bytes",
      "DataTransfer-Out-Bytes",
      "DataTransfer-Regional-Bytes",
      "EU-DataProcessing-Bytes",
      "EU-DataTransfer-In-Bytes",
      "EU-DataTransfer-Out-Bytes",
      "EU-DataTransfer-Out-OBytes",
      "EU-USE1-AWS-Out-Bytes",
      "EU-USW2-AWS-In-Bytes",
      "EU-USW2-AWS-Out-Bytes",
      "EUC1-DataProcessing-Bytes",
      "EUC1-DataTransfer-In-Bytes",
      "EUC1-DataTransfer-Out-Bytes",
      "EUC1-USE1-AWS-Out-Bytes",
      "EUC1-USW2-AWS-In-Bytes",
      "EUC1-USW2-AWS-Out-Bytes",
      "EUN1-DataTransfer-In-Bytes",
      "EUN1-DataTransfer-Out-Bytes",
      "EUN1-USE1-AWS-Out-Bytes",
      "EUN1-USW2-AWS-In-Bytes",
      "EUN1-USW2-AWS-Out-Bytes",
      "EUW2-DataProcessing-Bytes",
      "EUW2-DataTransfer-In-Bytes",
      "EUW2-DataTransfer-Out-Bytes",
      "EUW2-USE1-AWS-Out-Bytes",
      "EUW2-USW2-AWS-In-Bytes",
      "EUW2-USW2-AWS-Out-Bytes",
      "EUW3-DataTransfer-In-Bytes",
      "EUW3-DataTransfer-Out-Bytes",
      "EUW3-USE1-AWS-Out-Bytes",
      "EUW3-USW2-AWS-In-Bytes",
      "EUW3-USW2-AWS-Out-Bytes",
      "IN-DataTransfer-Out-Bytes",
      "IN-DataTransfer-Out-OBytes",
      "JP-DataTransfer-Out-Bytes",
      "JP-DataTransfer-Out-OBytes",
      "ME-DataTransfer-Out-Bytes",
      "ME-DataTransfer-Out-OBytes",
      "NA-AP-IN-Bytes-AWS",
      "NA-AP-IN-Bytes-Internet",
      "NA-AP-OUT-Bytes-AWS",
      "NA-AP-OUT-Bytes-Internet",
      "NA-AU-IN-Bytes-AWS",
      "NA-AU-IN-Bytes-Internet",
      "NA-AU-OUT-Bytes-AWS",
      "NA-AU-OUT-Bytes-Internet",
      "NA-EU-IN-Bytes-AWS",
      "NA-EU-IN-Bytes-Internet",
      "NA-EU-OUT-Bytes-AWS",
      "NA-EU-OUT-Bytes-Internet",
      "NA-IN-IN-Bytes-AWS",
      "NA-IN-IN-Bytes-Internet",
      "NA-IN-OUT-Bytes-AWS",
      "NA-IN-OUT-Bytes-Internet",
      "NA-KR-IN-Bytes-AWS",
      "NA-KR-IN-Bytes-Internet",
      "NA-KR-OUT-Bytes-AWS",
      "NA-KR-OUT-Bytes-Internet",
      "NA-ME-IN-Bytes-AWS",
      "NA-ME-IN-Bytes-Internet",
      "NA-ME-OUT-Bytes-AWS",
      "NA-ME-OUT-Bytes-Internet",
      "NA-NA-IN-Bytes-AWS",
      "NA-NA-IN-Bytes-Internet",
      "NA-NA-OUT-Bytes-AWS",
      "NA-NA-OUT-Bytes-Internet",
      "NA-SA-IN-Bytes-AWS",
      "NA-SA-IN-Bytes-Internet",
      "NA-SA-OUT-Bytes-AWS",
      "NA-SA-OUT-Bytes-Internet",
      "NA-ZA-IN-Bytes-AWS",
      "NA-ZA-IN-Bytes-Internet",
      "NA-ZA-OUT-Bytes-AWS",
      "NA-ZA-OUT-Bytes-Internet",
      "NatGateway-Bytes",
      "SA-DataTransfer-Out-Bytes",
      "SA-DataTransfer-Out-OBytes",
      "SAE1-DataProcessing-Bytes",
      "SAE1-DataTransfer-In-Bytes",
      "SAE1-DataTransfer-Out-Bytes",
      "SAE1-USE1-AWS-Out-Bytes",
      "SAE1-USW2-AWS-In-Bytes",
      "SAE1-USW2-AWS-Out-Bytes",
      "Select-Returned-Bytes",
      "Select-Scanned-Bytes",
      "US-DataTransfer-Out-Bytes",
      "US-DataTransfer-Out-OBytes",
      "USE1-AFS1-AWS-In-Bytes",
      "USE1-AFS1-AWS-Out-Bytes",
      "USE1-APE1-AWS-In-Bytes",
      "USE1-APE1-AWS-Out-Bytes",
      "USE1-APN1-AWS-In-Bytes",
      "USE1-APN1-AWS-Out-Bytes",
      "USE1-APN2-AWS-In-Bytes",
      "USE1-APN2-AWS-Out-Bytes",
      "USE1-APN3-AWS-In-Bytes",
      "USE1-APN3-AWS-Out-Bytes",
      "USE1-APNE1WL1KIX1-AWS-Out-Bytes",
      "USE1-APNE1WL1NRT1-AWS-Out-Bytes",
      "USE1-APNE2WL1CJJ1-AWS-Out-Bytes",
      "USE1-APNE2WL1SEL1-AWS-Out-Bytes",
      "USE1-APS1-AWS-In-Bytes",
      "USE1-APS1-AWS-Out-Bytes",
      "USE1-APS2-AWS-In-Bytes",
      "USE1-APS2-AWS-Out-Bytes",
      "USE1-APS3-AWS-In-Bytes",
      "USE1-APS3-AWS-Out-Bytes",
      "USE1-APS4-AWS-In-Bytes",
      "USE1-APS4-AWS-Out-Bytes",
      "USE1-APS5-AWS-In-Bytes",
      "USE1-APS5-AWS-Out-Bytes",
      "USE1-APS6-AWS-In-Bytes",
      "USE1-ATL1-AWS-Out-Bytes",
      "USE1-BKK1-AWS-In-Bytes",
      "USE1-BKK1-AWS-Out-Bytes",
      "USE1-BOS1-AWS-Out-Bytes",
      "USE1-BytesHr",
      "USE1-BytesIn",
      "USE1-BytesOut",
      "USE1-CAC1WL1YTO1-AWS-Out-Bytes",
      "USE1-CAN1-AWS-In-Bytes",
      "USE1-CAN1-AWS-Out-Bytes",
      "USE1-CCU1-AWS-In-Bytes",
      "USE1-CCU1-AWS-Out-Bytes",
      "USE1-CHI1-AWS-Out-Bytes",
      "USE1-CloudFront-In-Bytes",
      "USE1-CloudFront-Out-Bytes",
      "USE1-DEL1-AWS-In-Bytes",
      "USE1-DEL1-AWS-Out-Bytes",
      "USE1-DEN1-AWS-In-Bytes",
      "USE1-DEN1-AWS-Out-Bytes",
      "USE1-DFW1-AWS-Out-Bytes",
      "USE1-DataProcessing-Bytes",
      "USE1-DataScanned-Bytes",
      "USE1-DataTransfer-xAZ-In-Bytes",
      "USE1-DataTransfer-xAZ-Out-Bytes",
      "USE1-EU-AWS-In-Bytes",
      "USE1-EU-AWS-Out-Bytes",
      "USE1-EUC1-AWS-In-Bytes",
      "USE1-EUC1-AWS-Out-Bytes",
      "USE1-EUC1WL1BER1-AWS-Out-Bytes",
      "USE1-EUC1WL1MUC1-AWS-Out-Bytes",
      "USE1-EUC2-AWS-In-Bytes",
      "USE1-EUC2-AWS-Out-Bytes",
      "USE1-EUN1-AWS-In-Bytes",
      "USE1-EUN1-AWS-Out-Bytes",
      "USE1-EUS1-AWS-In-Bytes",
      "USE1-EUS1-AWS-Out-Bytes",
      "USE1-EUS2-AWS-In-Bytes",
      "USE1-EUS2-AWS-Out-Bytes",
      "USE1-EUW2-AWS-In-Bytes",
      "USE1-EUW2-AWS-Out-Bytes",
      "USE1-EUW2WL1LON1-AWS-Out-Bytes",
      "USE1-EUW3-AWS-In-Bytes",
      "USE1-EUW3-AWS-Out-Bytes",
      "USE1-HAM1-AWS-In-Bytes",
      "USE1-HAM1-AWS-Out-Bytes",
      "USE1-HEL1-AWS-Out-Bytes",
      "USE1-IAH1-AWS-Out-Bytes",
      "USE1-ILC1-AWS-In-Bytes",
      "USE1-LAS1-AWS-In-Bytes",
      "USE1-LAS1-AWS-Out-Bytes",
      "USE1-LAX1-AWS-In-Bytes",
      "USE1-LAX1-AWS-Out-Bytes",
      "USE1-LOS1-AWS-In-Bytes",
      "USE1-LOS1-AWS-Out-Bytes",
      "USE1-MCI2-AWS-Out-Bytes",
      "USE1-MCT1-AWS-In-Bytes",
      "USE1-MCT1-AWS-Out-Bytes",
      "USE1-MEC1-AWS-In-Bytes",
      "USE1-MEC1-AWS-Out-Bytes",
      "USE1-MES1-AWS-In-Bytes",
      "USE1-MES1-AWS-Out-Bytes",
      "USE1-MIA1-AWS-Out-Bytes",
      "USE1-MNL1-AWS-In-Bytes",
      "USE1-MNL1-AWS-Out-Bytes",
      "USE1-MSP1-AWS-Out-Bytes",
      "USE1-PDX1-AWS-In-Bytes",
      "USE1-PDX1-AWS-Out-Bytes",
      "USE1-PER1-AWS-Out-Bytes",
      "USE1-PHL1-AWS-Out-Bytes",
      "USE1-PHX1-AWS-In-Bytes",
      "USE1-PHX1-AWS-Out-Bytes",
      "USE1-SAE1-AWS-In-Bytes",
      "USE1-SAE1-AWS-Out-Bytes",
      "USE1-SEA1-AWS-In-Bytes",
      "USE1-SEA1-AWS-Out-Bytes",
      "USE1-TPE1-AWS-In-Bytes",
      "USE1-TPE1-AWS-Out-Bytes",
      "USE1-UGE1-AWS-Out-Bytes",
      "USE1-UGW1-AWS-Out-Bytes",
      "USE1-USE1WL1BWAS1-AWS-Out-Bytes",
      "USE1-USE1WL1NYC1-AWS-Out-Bytes",
      "USE1-USE2-AWS-In-Bytes",
      "USE1-USE2-AWS-Out-Bytes",
      "USE1-USW1-AWS-In-Bytes",
      "USE1-USW1-AWS-Out-Bytes",
      "USE1-USW2-AWS-In-Bytes",
      "USE1-USW2-AWS-Out-Bytes",
      "USE1-USW2WL1-AWS-Out-Bytes",
      "USE1-USW2WL1DEN1-AWS-Out-Bytes",
      "USE1-USW2WL1SEA1-AWS-Out-Bytes",
      "USE1-VendedLog-Bytes",
      "USE1-VpcEndpoint-Bytes",
      "USE1-WAW1-AWS-In-Bytes",
      "USE1-WAW1-AWS-Out-Bytes",
      "USE2-AFS1-AWS-In-Bytes",
      "USE2-AFS1-AWS-Out-Bytes",
      "USE2-AKL1-AWS-In-Bytes",
      "USE2-AKL1-AWS-Out-Bytes",
      "USE2-APE1-AWS-In-Bytes",
      "USE2-APE1-AWS-Out-Bytes",
      "USE2-APN1-AWS-In-Bytes",
      "USE2-APN1-AWS-Out-Bytes",
      "USE2-APN2-AWS-In-Bytes",
      "USE2-APN2-AWS-Out-Bytes",
      "USE2-APN3-AWS-In-Bytes",
      "USE2-APN3-AWS-Out-Bytes",
      "USE2-APNE1WL1NRT1-AWS-In-Bytes",
      "USE2-APNE1WL1NRT1-AWS-Out-Bytes",
      "USE2-APS1-AWS-In-Bytes",
      "USE2-APS1-AWS-Out-Bytes",
      "USE2-APS2-AWS-In-Bytes",
      "USE2-APS2-AWS-Out-Bytes",
      "USE2-APS3-AWS-In-Bytes",
      "USE2-APS3-AWS-Out-Bytes",
      "USE2-APS4-AWS-In-Bytes",
      "USE2-APS4-AWS-Out-Bytes",
      "USE2-APS5-AWS-In-Bytes",
      "USE2-APS5-AWS-Out-Bytes",
      "USE2-APS6-AWS-In-Bytes",
      "USE2-APS6-AWS-Out-Bytes",
      "USE2-ATL1-AWS-In-Bytes",
      "USE2-ATL1-AWS-Out-Bytes",
      "USE2-AWS-In-Bytes",
      "USE2-AWS-Out-Bytes",
      "USE2-BKK1-AWS-In-Bytes",
      "USE2-BKK1-AWS-Out-Bytes",
      "USE2-BOS1-AWS-In-Bytes",
      "USE2-BOS1-AWS-Out-Bytes",
      "USE2-BilledBytes",
      "USE2-BytesHr",
      "USE2-BytesIn",
      "USE2-BytesOut",
      "USE2-CAN1-AWS-In-Bytes",
      "USE2-CAN1-AWS-Out-Bytes",
      "USE2-CCU1-AWS-In-Bytes",
      "USE2-CCU1-AWS-Out-Bytes",
      "USE2-CHI1-AWS-In-Bytes",
      "USE2-CHI1-AWS-Out-Bytes",
      "USE2-CloudFront-In-Bytes",
      "USE2-CloudFront-Out-Bytes",
      "USE2-DEL1-AWS-In-Bytes",
      "USE2-DEL1-AWS-Out-Bytes",
      "USE2-DEN1-AWS-In-Bytes",
      "USE2-DEN1-AWS-Out-Bytes",
      "USE2-DFW1-AWS-In-Bytes",
      "USE2-DFW1-AWS-Out-Bytes",
      "USE2-DataProcessing-Bytes",
      "USE2-DataScanned-Bytes",
      "USE2-DataTransfer-AZ-In-Bytes",
      "USE2-DataTransfer-AZ-Out-Bytes",
      "USE2-DataTransfer-In-Bytes",
      "USE2-DataTransfer-Out-Bytes",
      "USE2-DataTransfer-Regional-Bytes",
      "USE2-DataTransfer-xAZ-In-Bytes",
      "USE2-DataTransfer-xAZ-Out-Bytes",
      "USE2-EU-AWS-In-Bytes",
      "USE2-EU-AWS-Out-Bytes",
      "USE2-EUC1-AWS-In-Bytes",
      "USE2-EUC1-AWS-Out-Bytes",
      "USE2-EUC2-AWS-In-Bytes",
      "USE2-EUC2-AWS-Out-Bytes",
      "USE2-EUN1-AWS-In-Bytes",
      "USE2-EUN1-AWS-Out-Bytes",
      "USE2-EUS1-AWS-In-Bytes",
      "USE2-EUS1-AWS-Out-Bytes",
      "USE2-EUS2-AWS-In-Bytes",
      "USE2-EUS2-AWS-Out-Bytes",
      "USE2-EUW2-AWS-In-Bytes",
      "USE2-EUW2-AWS-Out-Bytes",
      "USE2-EUW3-AWS-In-Bytes",
      "USE2-EUW3-AWS-Out-Bytes",
      "USE2-ExportDataSize-Bytes",
      "USE2-HAM1-AWS-In-Bytes",
      "USE2-HAM1-AWS-Out-Bytes",
      "USE2-IADataAccess-Bytes",
      "USE2-IAH1-AWS-In-Bytes",
      "USE2-IAH1-AWS-Out-Bytes",
      "USE2-ILC1-AWS-In-Bytes",
      "USE2-ILC1-AWS-Out-Bytes",
      "USE2-LAS1-AWS-In-Bytes",
      "USE2-LAS1-AWS-Out-Bytes",
      "USE2-LAX1-AWS-In-Bytes",
      "USE2-LAX1-AWS-Out-Bytes",
      "USE2-LIM1-AWS-In-Bytes",
      "USE2-LIM1-AWS-Out-Bytes",
      "USE2-LOS1-AWS-In-Bytes",
      "USE2-LOS1-AWS-Out-Bytes",
      "USE2-MCI2-AWS-In-Bytes",
      "USE2-MCI2-AWS-Out-Bytes",
      "USE2-MCT1-AWS-In-Bytes",
      "USE2-MCT1-AWS-Out-Bytes",
      "USE2-MEC1-AWS-In-Bytes",
      "USE2-MEC1-AWS-Out-Bytes",
      "USE2-MES1-AWS-In-Bytes",
      "USE2-MES1-AWS-Out-Bytes",
      "USE2-MIA1-AWS-In-Bytes",
      "USE2-MIA1-AWS-Out-Bytes",
      "USE2-MNL1-AWS-In-Bytes",
      "USE2-MNL1-AWS-Out-Bytes",
      "USE2-MSP1-AWS-In-Bytes",
      "USE2-MSP1-AWS-Out-Bytes",
      "USE2-NYC1-AWS-In-Bytes",
      "USE2-NYC1-AWS-Out-Bytes",
      "USE2-NatGateway-Bytes",
      "USE2-PDX1-AWS-In-Bytes",
      "USE2-PDX1-AWS-Out-Bytes",
      "USE2-PER1-AWS-In-Bytes",
      "USE2-PER1-AWS-Out-Bytes",
      "USE2-PHL1-AWS-In-Bytes",
      "USE2-PHL1-AWS-Out-Bytes",
      "USE2-PHX1-AWS-In-Bytes",
      "USE2-PHX1-AWS-Out-Bytes",
      "USE2-QRO1-AWS-In-Bytes",
      "USE2-QRO1-AWS-Out-Bytes",
      "USE2-S3-Egress-Bytes",
      "USE2-SAE1-AWS-In-Bytes",
      "USE2-SAE1-AWS-Out-Bytes",
      "USE2-SCL1-AWS-In-Bytes",
      "USE2-SCL1-AWS-Out-Bytes",
      "USE2-SEA1-AWS-In-Bytes",
      "USE2-SEA1-AWS-Out-Bytes",
      "USE2-TPE1-AWS-In-Bytes",
      "USE2-TPE1-AWS-Out-Bytes",
      "USE2-UGE1-AWS-In-Bytes",
      "USE2-UGE1-AWS-Out-Bytes",
      "USE2-UGW1-AWS-In-Bytes",
      "USE2-UGW1-AWS-Out-Bytes",
      "USE2-USE1-AWS-In-Bytes",
      "USE2-USE1-AWS-Out-Bytes",
      "USE2-USW1-AWS-In-Bytes",
      "USE2-USW1-AWS-Out-Bytes",
      "USE2-USW2-AWS-In-Bytes",
      "USE2-USW2-AWS-Out-Bytes",
      "USE2-VendedLog-Bytes",
      "USE2-VpcEndpoint-Bytes",
      "USE2-WAW1-AWS-In-Bytes",
      "USE2-WAW1-AWS-Out-Bytes",
      "USW1-AFS1-AWS-In-Bytes",
      "USW1-AFS1-AWS-Out-Bytes",
      "USW1-APE1-AWS-In-Bytes",
      "USW1-APE1-AWS-Out-Bytes",
      "USW1-APN1-AWS-In-Bytes",
      "USW1-APN1-AWS-Out-Bytes",
      "USW1-APN2-AWS-In-Bytes",
      "USW1-APN2-AWS-Out-Bytes",
      "USW1-APN3-AWS-In-Bytes",
      "USW1-APN3-AWS-Out-Bytes",
      "USW1-APS1-AWS-In-Bytes",
      "USW1-APS1-AWS-Out-Bytes",
      "USW1-APS2-AWS-In-Bytes",
      "USW1-APS2-AWS-Out-Bytes",
      "USW1-APS3-AWS-In-Bytes",
      "USW1-APS3-AWS-Out-Bytes",
      "USW1-APS4-AWS-In-Bytes",
      "USW1-APS4-AWS-Out-Bytes",
      "USW1-APS5-AWS-In-Bytes",
      "USW1-APS5-AWS-Out-Bytes",
      "USW1-CAN1-AWS-In-Bytes",
      "USW1-CAN1-AWS-Out-Bytes",
      "USW1-CloudFront-In-Bytes",
      "USW1-CloudFront-Out-Bytes",
      "USW1-DataProcessing-Bytes",
      "USW1-DataScanned-Bytes",
      "USW1-DataTransfer-In-Bytes",
      "USW1-DataTransfer-Out-Bytes",
      "USW1-DataTransfer-Regional-Bytes",
      "USW1-EU-AWS-In-Bytes",
      "USW1-EU-AWS-Out-Bytes",
      "USW1-EUC1-AWS-In-Bytes",
      "USW1-EUC1-AWS-Out-Bytes",
      "USW1-EUC2-AWS-In-Bytes",
      "USW1-EUC2-AWS-Out-Bytes",
      "USW1-EUN1-AWS-In-Bytes",
      "USW1-EUN1-AWS-Out-Bytes",
      "USW1-EUW2-AWS-In-Bytes",
      "USW1-EUW2-AWS-Out-Bytes",
      "USW1-EUW3-AWS-In-Bytes",
      "USW1-EUW3-AWS-Out-Bytes",
      "USW1-MEC1-AWS-In-Bytes",
      "USW1-MEC1-AWS-Out-Bytes",
      "USW1-SAE1-AWS-In-Bytes",
      "USW1-SAE1-AWS-Out-Bytes",
      "USW1-UGW1-AWS-In-Bytes",
      "USW1-UGW1-AWS-Out-Bytes",
      "USW1-USE1-AWS-In-Bytes",
      "USW1-USE1-AWS-Out-Bytes",
      "USW1-USE2-AWS-In-Bytes",
      "USW1-USE2-AWS-Out-Bytes",
      "USW1-USW2-AWS-In-Bytes",
      "USW1-USW2-AWS-Out-Bytes",
      "USW2-AFS1-AWS-In-Bytes",
      "USW2-AFS1-AWS-Out-Bytes",
      "USW2-AKL1-AWS-In-Bytes",
      "USW2-AKL1-AWS-Out-Bytes",
      "USW2-APE1-AWS-In-Bytes",
      "USW2-APE1-AWS-Out-Bytes",
      "USW2-APN1-AWS-In-Bytes",
      "USW2-APN1-AWS-Out-Bytes",
      "USW2-APN2-AWS-In-Bytes",
      "USW2-APN2-AWS-Out-Bytes",
      "USW2-APN3-AWS-In-Bytes",
      "USW2-APN3-AWS-Out-Bytes",
      "USW2-APNE1WL1KIX1-AWS-In-Bytes",
      "USW2-APNE1WL1KIX1-AWS-Out-Bytes",
      "USW2-APNE1WL1NRT1-AWS-In-Bytes",
      "USW2-APNE1WL1NRT1-AWS-Out-Bytes",
      "USW2-APNE2WL1CJJ1-AWS-In-Bytes",
      "USW2-APNE2WL1CJJ1-AWS-Out-Bytes",
      "USW2-APNE2WL1SEL1-AWS-In-Bytes",
      "USW2-APNE2WL1SEL1-AWS-Out-Bytes",
      "USW2-APS1-AWS-In-Bytes",
      "USW2-APS1-AWS-Out-Bytes",
      "USW2-APS2-AWS-In-Bytes",
      "USW2-APS2-AWS-Out-Bytes",
      "USW2-APS3-AWS-In-Bytes",
      "USW2-APS3-AWS-Out-Bytes",
      "USW2-APS4-AWS-In-Bytes",
      "USW2-APS4-AWS-Out-Bytes",
      "USW2-APS5-AWS-In-Bytes",
      "USW2-APS5-AWS-Out-Bytes",
      "USW2-APS6-AWS-In-Bytes",
      "USW2-APS6-AWS-Out-Bytes",
      "USW2-ATL1-AWS-In-Bytes",
      "USW2-ATL1-AWS-Out-Bytes",
      "USW2-AWS-In-Bytes",
      "USW2-AWS-Out-Bytes",
      "USW2-BKK1-AWS-In-Bytes",
      "USW2-BKK1-AWS-Out-Bytes",
      "USW2-BOS1-AWS-In-Bytes",
      "USW2-BOS1-AWS-Out-Bytes",
      "USW2-BilledBytes",
      "USW2-BytesHr",
      "USW2-BytesIn",
      "USW2-BytesOut",
      "USW2-CAC1WL1YTO1-AWS-In-Bytes",
      "USW2-CAC1WL1YTO1-AWS-Out-Bytes",
      "USW2-CAN1-AWS-In-Bytes",
      "USW2-CAN1-AWS-Out-Bytes",
      "USW2-CCU1-AWS-In-Bytes",
      "USW2-CCU1-AWS-Out-Bytes",
      "USW2-CHI1-AWS-In-Bytes",
      "USW2-CHI1-AWS-Out-Bytes",
      "USW2-CloudFront-In-Bytes",
      "USW2-CloudFront-Out-Bytes",
      "USW2-CloudFrontChina-In-Bytes",
      "USW2-CloudFrontChina-Out-Bytes",
      "USW2-ContainerSvc:TotalDataXfer-In-Bytes",
      "USW2-ContainerSvc:TotalDataXfer-Out-Bytes",
      "USW2-DEL1-AWS-In-Bytes",
      "USW2-DEL1-AWS-Out-Bytes",
      "USW2-DEN1-AWS-In-Bytes",
      "USW2-DEN1-AWS-Out-Bytes",
      "USW2-DFW1-AWS-In-Bytes",
      "USW2-DFW1-AWS-Out-Bytes",
      "USW2-DataProcessing-Bytes",
      "USW2-DataScanned-Bytes",
      "USW2-DataTransfer-AZ-In-Bytes",
      "USW2-DataTransfer-AZ-Out-Bytes",
      "USW2-DataTransfer-In-Bytes",
      "USW2-DataTransfer-Out-Bytes",
      "USW2-DataTransfer-Regional-Bytes",
      "USW2-DataTransfer-xAZ-In-Bytes",
      "USW2-DataTransfer-xAZ-Out-Bytes",
      "USW2-EU-AWS-In-Bytes",
      "USW2-EU-AWS-Out-Bytes",
      "USW2-EUC1-AWS-In-Bytes",
      "USW2-EUC1-AWS-Out-Bytes",
      "USW2-EUC1WL1BER1-AWS-In-Bytes",
      "USW2-EUC1WL1BER1-AWS-Out-Bytes",
      "USW2-EUC1WL1DTM1-AWS-In-Bytes",
      "USW2-EUC1WL1DTM1-AWS-Out-Bytes",
      "USW2-EUC1WL1MUC1-AWS-In-Bytes",
      "USW2-EUC1WL1MUC1-AWS-Out-Bytes",
      "USW2-EUC2-AWS-In-Bytes",
      "USW2-EUC2-AWS-Out-Bytes",
      "USW2-EUN1-AWS-In-Bytes",
      "USW2-EUN1-AWS-Out-Bytes",
      "USW2-EUS1-AWS-In-Bytes",
      "USW2-EUS1-AWS-Out-Bytes",
      "USW2-EUS2-AWS-In-Bytes",
      "USW2-EUS2-AWS-Out-Bytes",
      "USW2-EUW2-AWS-In-Bytes",
      "USW2-EUW2-AWS-Out-Bytes",
      "USW2-EUW2WL1LON1-AWS-In-Bytes",
      "USW2-EUW2WL1LON1-AWS-Out-Bytes",
      "USW2-EUW3-AWS-In-Bytes",
      "USW2-EUW3-AWS-Out-Bytes",
      "USW2-ExportDataSize-Bytes",
      "USW2-FreeTrialIngestion-Bytes",
      "USW2-FreeTrialQueryScanned-Bytes",
      "USW2-HAM1-AWS-In-Bytes",
      "USW2-HAM1-AWS-Out-Bytes",
      "USW2-HEL1-AWS-In-Bytes",
      "USW2-HEL1-AWS-Out-Bytes",
      "USW2-Hst:Data-Bytes-In",
      "USW2-Hst:Data-Bytes-Out",
      "USW2-IADataAccess-Bytes",
      "USW2-IAH1-AWS-In-Bytes",
      "USW2-IAH1-AWS-Out-Bytes",
      "USW2-ILC1-AWS-In-Bytes",
      "USW2-ILC1-AWS-Out-Bytes",
      "USW2-ImportDataSize-Bytes",
      "USW2-LAS1-AWS-In-Bytes",
      "USW2-LAS1-AWS-Out-Bytes",
      "USW2-LIM1-AWS-In-Bytes",
      "USW2-LIM1-AWS-Out-Bytes",
      "USW2-LOS1-AWS-In-Bytes",
      "USW2-LOS1-AWS-Out-Bytes",
      "USW2-MCI2-AWS-In-Bytes",
      "USW2-MCI2-AWS-Out-Bytes",
      "USW2-MCT1-AWS-In-Bytes",
      "USW2-MCT1-AWS-Out-Bytes",
      "USW2-MEC1-AWS-In-Bytes",
      "USW2-MEC1-AWS-Out-Bytes",
      "USW2-MES1-AWS-In-Bytes",
      "USW2-MES1-AWS-Out-Bytes",
      "USW2-MIA1-AWS-In-Bytes",
      "USW2-MIA1-AWS-Out-Bytes",
      "USW2-MNL1-AWS-In-Bytes",
      "USW2-MNL1-AWS-Out-Bytes",
      "USW2-MSP1-AWS-In-Bytes",
      "USW2-MSP1-AWS-Out-Bytes",
      "USW2-NYC1-AWS-In-Bytes",
      "USW2-NYC1-AWS-Out-Bytes",
      "USW2-NatGateway-Bytes",
      "USW2-OnDemand-BilledIncomingBytes",
      "USW2-OnDemand-BilledOutgoingBytes",
      "USW2-PER1-AWS-In-Bytes",
      "USW2-PER1-AWS-Out-Bytes",
      "USW2-PHL1-AWS-In-Bytes",
      "USW2-PHL1-AWS-Out-Bytes",
      "USW2-PHX1-AWS-Out-Bytes",
      "USW2-PaidEventsAnalyzed-Bytes",
      "USW2-QRO1-AWS-In-Bytes",
      "USW2-QRO1-AWS-Out-Bytes",
      "USW2-S3-Egress-Bytes",
      "USW2-SAE1-AWS-In-Bytes",
      "USW2-SAE1-AWS-Out-Bytes",
      "USW2-SCL1-AWS-In-Bytes",
      "USW2-SCL1-AWS-Out-Bytes",
      "USW2-SEA1-AWS-Out-Bytes",
      "USW2-TPE1-AWS-In-Bytes",
      "USW2-TPE1-AWS-Out-Bytes",
      "USW2-UGE1-AWS-In-Bytes",
      "USW2-UGE1-AWS-Out-Bytes",
      "USW2-UGW1-AWS-In-Bytes",
      "USW2-UGW1-AWS-Out-Bytes",
      "USW2-USE1-AWS-In-Bytes",
      "USW2-USE1-AWS-Out-Bytes",
      "USW2-USE1WL1-AWS-Out-Bytes",
      "USW2-USE1WL1ATL1-AWS-Out-Bytes",
      "USW2-USE1WL1BWAS1-AWS-Out-Bytes",
      "USW2-USE1WL1CHI1-AWS-In-Bytes",
      "USW2-USE1WL1CHI1-AWS-Out-Bytes",
      "USW2-USE1WL1IAH1-AWS-In-Bytes",
      "USW2-USE1WL1IAH1-AWS-Out-Bytes",
      "USW2-USE1WL1MSP1-AWS-In-Bytes",
      "USW2-USE1WL1MSP1-AWS-Out-Bytes",
      "USW2-USE1WL1NYC1-AWS-In-Bytes",
      "USW2-USE1WL1NYC1-AWS-Out-Bytes",
      "USW2-USE2-AWS-In-Bytes",
      "USW2-USE2-AWS-Out-Bytes",
      "USW2-USW1-AWS-In-Bytes",
      "USW2-USW1-AWS-Out-Bytes",
      "USW2-USW2WL1-AWS-In-Bytes",
      "USW2-USW2WL1-AWS-Out-Bytes",
      "USW2-USW2WL1DEN1-AWS-In-Bytes",
      "USW2-USW2WL1DEN1-AWS-Out-Bytes",
      "USW2-USW2WL1LAS1-AWS-In-Bytes",
      "USW2-USW2WL1LAS1-AWS-Out-Bytes",
      "USW2-USW2WL1PHX1-AWS-Out-Bytes",
      "USW2-USW2WL1SEA1-AWS-In-Bytes",
      "USW2-USW2WL1SEA1-AWS-Out-Bytes",
      "USW2-VendedLog-Bytes",
      "USW2-VpcEndpoint-Bytes",
      "USW2-WAW1-AWS-In-Bytes",
      "USW2-WAW1-AWS-Out-Bytes",
      "ZA-DataTransfer-Out-Bytes",
      "ZA-DataTransfer-Out-OBytes",
    ]
  }

  ALL_SERVICES = [
    APN_ANNUAL_PROGRAM_FEE = "APN Annual Program Fee",
    AWS_BACKUP = "AWS Backup",
    AWS_CLOUD_MAP = "AWS Cloud Map",
    AWS_CLOUDSHELL = "AWS CloudShell",
    AWS_CLOUDTRAIL = "AWS CloudTrail",
    AWS_CODEARTIFACT = "AWS CodeArtifact",
    AWS_CODECOMMIT = "AWS CodeCommit",
    AWS_CODEPIPELINE = "AWS CodePipeline",
    AWS_COST_EXPLORER = "AWS Cost Explorer",
    AWS_DATA_TRANSFER = "AWS Data Transfer",
    AWS_DATABASE_MIGRATION_SERVICE = "AWS Database Migration Service",
    AWS_ELEMENTAL_MEDIASTORE = "AWS Elemental MediaStore",
    AWS_GLOBAL_ACCELERATOR = "AWS Global Accelerator",
    AWS_GLUE = "AWS Glue",
    AWS_IOT = "AWS IoT",
    AWS_KEY_MANAGEMENT_SERVICE = "AWS Key Management Service",
    AWS_LAMBDA = "AWS Lambda",
    AWS_MIGRATION_HUB_REFACTOR_SPACES = "AWS Migration Hub Refactor Spaces",
    AWS_PREMIUM_SUPPORT = "AWS Premium Support",
    AWS_SECRETS_MANAGER = "AWS Secrets Manager",
    AWS_SERVICE_CATALOG = "AWS Service Catalog",
    AWS_STEP_FUNCTIONS = "AWS Step Functions",
    AWS_SUPPORT_ENTERPRISE = "AWS Support (Enterprise)",
    AWS_SYSTEMS_MANAGER = "AWS Systems Manager",
    AWS_WAF = "AWS WAF",
    AWS_X_RAY = "AWS X-Ray",
    AMAZON_API_GATEWAY = "Amazon API Gateway",
    AMAZON_ATHENA = "Amazon Athena",
    AMAZON_CLOUDFRONT = "Amazon CloudFront",
    AMAZON_COMPREHEND = "Amazon Comprehend",
    AMAZON_DATAZONE = "Amazon DataZone",
    AMAZON_DEVOPS_GURU = "Amazon DevOps Guru",
    AMAZON_DYNAMODB = "Amazon DynamoDB",
    AMAZON_EC2_CONTAINER_REGISTRY = "Amazon EC2 Container Registry (ECR)",
    AMAZON_ELASTICACHE = "Amazon ElastiCache",
    EC2_OTHER = "EC2 - Other",
    AMAZON_ELASTIC_COMPUTE_CLOUD_COMPUTE = "Amazon Elastic Compute Cloud - Compute",
    AMAZON_ELASTIC_CONTAINER_SERVICE = "Amazon Elastic Container Service",
    AMAZON_ELASTIC_CONTAINER_SERVICE_FOR_KUBERNETES = "Amazon Elastic Container Service for Kubernetes",
    AMAZON_ELASTIC_FILE_SYSTEM = "Amazon Elastic File System",
    AMAZON_ELASTIC_LOAD_BALANCING = "Amazon Elastic Load Balancing",
    AMAZON_ELASTIC_MAPREDUCE = "Amazon Elastic MapReduce",
    AMAZON_GLACIER = "Amazon Glacier",
    AMAZON_GUARDDUTY = "Amazon GuardDuty",
    AMAZON_INSPECTOR = "Amazon Inspector",
    AMAZON_KINESIS = "Amazon Kinesis",
    AMAZON_KINESIS_ANALYTICS = "Amazon Kinesis Analytics",
    AMAZON_KINESIS_FIREHOSE = "Amazon Kinesis Firehose",
    AMAZON_KINESIS_VIDEO_STREAMS = "Amazon Kinesis Video Streams",
    AMAZON_LIGHTSAIL = "Amazon Lightsail",
    AMAZON_MANAGED_STREAMING_FOR_APACHE_KAFKA = "Amazon Managed Streaming for Apache Kafka",
    AMAZON_MANAGED_WORKFLOWS_FOR_APACHE_AIRFLOW = "Amazon Managed Workflows for Apache Airflow",
    AMAZON_OPENSEARCH_SERVICE = "Amazon OpenSearch Service",
    AMAZON_RELATIONAL_DATABASE_SERVICE = "Amazon Relational Database Service",
    AMAZON_ROUTE_53 = "Amazon Route 53",
    AMAZON_SAGEMAKER = "Amazon SageMaker",
    AMAZON_SIMPLE_NOTIFICATION_SERVICE = "Amazon Simple Notification Service",
    AMAZON_SIMPLE_QUEUE_SERVICE = "Amazon Simple Queue Service",
    AMAZON_SIMPLE_STORAGE_SERVICE = "Amazon Simple Storage Service",
    AMAZON_SIMPLE_WORKFLOW_SERVICE = "Amazon Simple Workflow Service",
    AMAZON_SIMPLEDB = "Amazon SimpleDB",
    AMAZON_TEXTRACT = "Amazon Textract",
    AMAZON_TRANSCRIBE = "Amazon Transcribe",
    AMAZON_TRANSLATE = "Amazon Translate",
    AMAZON_VIRTUAL_PRIVATE_CLOUD = "Amazon Virtual Private Cloud",
    AMAZON_WORKSPACES = "Amazon WorkSpaces",
    AMAZONCLOUDWATCH_ = "AmazonCloudWatch",
    APACHE_KAFKA_ON_CONFLUENT_CLOUD_ANNUAL_COMMITS = "Apache Kafka® on Confluent Cloud™ - Annual Commits",
    CIRCLECI_CLOUD_HOSTED_CI_CD = "CircleCI - Cloud-Hosted CI/CD",
    CLOUDWATCH_EVENTS = "CloudWatch Events",
    CODEBUILD_ = "CodeBuild",
    CODEGURU_ = "CodeGuru",
    COHERE_RERANK_MODEL_MULTILINGUAL = "Cohere Rerank Model - Multilingual",
    NOTION = "Notion",
    OUT_OF_CYCLE_BILLING_DATATRANSFER = "Out of Cycle Billing - DataTransfer",
    PINECONE = "Pinecone Vector Database - Annual Commits",
    REFUND = "Refund",
    SAVINGS_PLANS_FOR_AWS_COMPUTE_USAGE = "Savings Plans for AWS Compute usage",
    TAX = "Tax",
    WIZ_CLOUD_INFRASTRUCTURE_SECURITY_PLATFORM = "WIZ Cloud Infrastructure Security Platform",
  ]

  SERVICES_TO_IGNORE = [
    APN_ANNUAL_PROGRAM_FEE,
    AWS_PREMIUM_SUPPORT,
    AWS_SUPPORT_ENTERPRISE,
    APACHE_KAFKA_ON_CONFLUENT_CLOUD_ANNUAL_COMMITS,
    CIRCLECI_CLOUD_HOSTED_CI_CD,
    COHERE_RERANK_MODEL_MULTILINGUAL,
    NOTION,
    OUT_OF_CYCLE_BILLING_DATATRANSFER,
    PINECONE,
    REFUND,
    SAVINGS_PLANS_FOR_AWS_COMPUTE_USAGE,
    TAX,
    WIZ_CLOUD_INFRASTRUCTURE_SECURITY_PLATFORM,
  ]

  EXCLUDE_IGNORED_SERVICES_FILTER = {
    not: { dimensions: { key: "SERVICE", values: SERVICES_TO_IGNORE } }
  }

  IGNORED_SERVICES_ONLY_FILTER = {
    dimensions: { key: "SERVICE", values: SERVICES_TO_IGNORE }
  }

  IGNORED_SERVICES_FOR_FORECAST_FILTER = {
    dimensions: { key: "SERVICE", values: SERVICES_TO_IGNORE.excluding(SAVINGS_PLANS_FOR_AWS_COMPUTE_USAGE) }
  }

  CSP_ONLY_USAGE_FILTER = {
    dimensions: { key: "PURCHASE_TYPE", values: ["Savings Plans"] }
  }

  CSP_ELIGIBLE_COST_AND_USAGE_FILTER = {
    and: [
      { dimensions: { key: "PURCHASE_TYPE", values: ["On Demand Instances"] } },
      {
        dimensions: {
          key: "SERVICE",
          values: [
            "Amazon Elastic Compute Cloud - Compute",
            "AWS Lambda",
            "Amazon Elastic Container Service",
            "Amazon Elastic Container Service for Kubernetes",
            "Amazon SageMaker"
          ]
        }
      },
      # Temp solution. Figure out why we can't use wildcard
      { not: { dimensions: { key: "USAGE_TYPE", values: USAGE_TYPES[:TOP_DATA_TRANSFER] } } }
    # { not: { dimensions: { key: "USAGE_TYPE", values: ["*Bytes*"] } } }
    ]
  }
end
